import React from 'react'
import { PlaceholderLayout } from './PlaceholderLayout'

export default function TermsOfService() {
  return (
    <PlaceholderLayout title="DatingPool Terms and Conditions of Use">
      <div className="terms-content">
        <p>
          Welcome to DatingPool's Terms and Conditions of Use (these "Terms"). The Terms constitute a binding legal agreement between you as a user ("you") and the DatingPool, LLC ("we," "us," or "DatingPool") and we want you to know yours and our rights before you use the DatingPool website or application (the "App"). Please take a few moments to read these Terms before enjoying the App, because once you access, view or use the App, you are going to be legally bound by these Terms. Please also read our Community Guidelines (which form part of these Terms) and our Privacy Policy.
        </p>
        <p>
          Please be aware that if you subscribe to services for a term (the "Initial Term"), then the terms of your subscription will be automatically renewed for additional periods of the same duration as the Initial Term at DatingPool's then-current fee for such services, unless you cancel your subscription in accordance with Section 6 (Payment Terms) below.
        </p>
        <p>
          You should also note that Section 14 of these Terms contains provisions governing how claims that you and DatingPool Group have against each other are resolved. In particular, it contains an arbitration agreement that will, with limited exceptions, require disputes between us to be submitted to binding and final arbitration. You have a right to opt out of the arbitration agreement pursuant to Section 14 below. If you do not opt out of the arbitration agreement in accordance with Section 14, (1) you will only be permitted to pursue claims and seek relief against us on an individual basis only; and (2) you are waiving your right to seek relief in a court of law and to have a jury trial on your claims.
        </p>
        <p>
          And a notice to California subscribers: You may cancel your subscription and request a refund at any time prior to midnight of the third business day following the date you subscribed. If you subscribed using your Apple ID, refunds are handled by Apple, not DatingPool. If you wish to request a refund, please visit Apple Support. If you subscribed using your Google Play Store account or through DatingPool, please contact customer support.
        </p>
        <p><strong>Effective date:</strong> The Terms were last updated on February 4, 2026.</p>

        <h2>1. DATINGPOOL RULES</h2>
        <p>Before you can use the App, you will need to register for an account ("Account"). In order to create an Account you must:</p>
        <ul>
          <li>be at least 18 years old or the age of majority to legally enter into a contract under the laws of your home country if that happens to be greater than 18; and</li>
          <li>be legally permitted to use the App by the laws of your home country.</li>
        </ul>
        <p>Please note that we monitor for underage use and we will terminate, suspend or ask you to verify your Account if we have reason to believe that you may be underage.</p>
        <p>You can create an Account via manual registration, or by using your Facebook login details. If you create an Account using your Facebook login details, you authorize us to access, display and use certain information from your Facebook account (e.g. profile pictures, relationship status, location and information about Facebook friends).</p>
        <p>You cannot use another person's DatingPool account or share your DatingPool account with any other person without our permission. You are responsible for ensuring that any use of your account complies with these Terms.</p>
        <p>You can delete your Account at any time by going to the 'Settings' page when you are logged in and clicking on the 'Delete account' link. Your Account will be deleted immediately but it may take a little while for Your Content (defined below) to be completely removed from the App. If you delete your Account and try to create a new account within this time period using the same credentials, we will re-activate your Account for you.</p>
        <p>We reserve the right at our sole discretion to terminate or suspend any Account, restrict access to the App, or make use of any operational, technological, legal or other means available to enforce the Terms (including without limitation blocking specific IP addresses). We may take such action, at any time without liability and without the need to give you prior notice. Without limiting the foregoing in any way, we expressly reserve the right to terminate or suspend your Account without notice (1) for violating these Terms, (2) due to your conduct on the App, or your conduct with other users of the App (including your "offline" conduct), if we, in our sole discretion, determine your conduct was inappropriate or improper, (3) if we or our affiliates, in our or their sole discretion, determine your conduct on other apps operated by our affiliates was inappropriate or improper, or (4) for any reasons whatsoever that we deem, in our sole discretion, justifies termination. If your Account is terminated or suspended, you agree you will not receive a refund for any paid service or features you have already been charged for. If you believe that we've made a mistake in taking action on your Account or Your Content (defined below), you have the option to appeal our decision within a six-month period. If you wish to appeal a decision, please start by taking a moment to read the relevant section of our Community Guidelines. If you still think there has been a mistake in the action taken on your account or content, the best way to appeal is to fill out the appeals form linked in the notification shown to you within the App at the time. Alternatively, you can contact us (please explain why you are appealing our decision and give as much detail as you can).</p>
        <p>You may not access, tamper with, or use non-public areas of the App or our systems. Certain portions of the App may not be accessible if you have not registered for an Account.</p>

        <h2>2. TYPES OF CONTENT</h2>
        <p>There are three types of content that you will be able to access on the App:</p>
        <ul>
          <li>content that you upload and provide ("Your Content");</li>
          <li>content that other members provide ("Member Content"); and</li>
          <li>content that the DatingPool provides (including, without limitation, database(s) and/or software) ("Our Content").</li>
        </ul>
        <p>There is certain content we can't allow on DatingPool. Our Community Guidelines form part of these Terms and outline what content and conduct is accepted on and off our App. You agree to comply with our Community Guidelines as may be updated from time to time.</p>
        <p>We want our users to be able express themselves as much as possible on DatingPool, but we have to impose restrictions on certain content which:</p>
        <ul>
          <li>is illegal or encourages, promotes or incites any illegal activity;</li>
          <li>is harmful to minors;</li>
          <li>is defamatory or libelous;</li>
          <li>itself, or the posting of which, infringes any third party's rights (including, without limitation, intellectual property rights and privacy rights);</li>
          <li>shows another person which was created or distributed without that person's consent;</li>
          <li>contains language or imagery which could be deemed offensive or is likely to harass, upset, embarrass, alarm or annoy any other person;</li>
          <li>is obscene, pornographic, violent or otherwise may offend human dignity;</li>
          <li>is abusive, insulting or threatening, discriminatory or which promotes or encourages racism, sexism, hatred or bigotry;</li>
          <li>relates to commercial activities (including, without limitation, sales, competitions and advertising, links to other websites or premium line telephone numbers);</li>
          <li>involves the transmission of "junk" mail or "spam";</li>
          <li>impersonates or intends to deceive or manipulate a person (including, without limitation, scams and inauthentic behavior);</li>
          <li>contains any spyware, adware, viruses, corrupt files, worm programs or other malicious code designed to interrupt, damage or limit the functionality of or disrupt any software, hardware, telecommunications, networks, servers or other equipment, Trojan horse or any other material designed to damage, interfere with, wrongly intercept or expropriate any data or personal information whether from DatingPool or otherwise; or</li>
          <li>in any other way violates our Community Guidelines.</li>
        </ul>

        <h3>Your Content</h3>
        <p>You agree that Your Content must comply with our Community Guidelines as updated from time to time.</p>
        <p>As Your Content is unique, you are responsible and liable for Your Content. You will indemnify, defend, release, and hold us harmless from any claims made in connection with Your Content.</p>
        <p>You may not display any personal contact or banking information on your individual profile page whether in relation to you or any other person (for example, names, home addresses or postcodes, telephone numbers, email addresses, URLs, credit/debit card or other banking details). If you do choose to reveal any personal information about yourself to other users, whether via email or otherwise, it is at your own risk.</p>
        <p>As DatingPool is a public community, Your Content will be visible to other users of the App. As such, you agree that Your Content may be viewed by other users and any person visiting, participating in or who is sent a link to the App. By uploading Your Content on DatingPool, you represent and warrant to us that you have all necessary rights and licenses to do so, and automatically grant us a non-exclusive, royalty free, perpetual, worldwide license to use Your Content in any way (including, without limitation, editing, copying, modifying, adapting, translating, reformatting, creating derivative works from, incorporating into other works, advertising, distributing and otherwise making available to the general public such content, whether in whole or in part and in any format or medium currently known or developed in the future). We may assign and/or sub-license the above license to our affiliates and successors without any further approval by you. We do not have any obligation to store Your Content.</p>
        <p>So that we can prevent the unconsented use of Your Content by other members or third parties outside of DatingPool, you authorize us to act on your behalf with respect to such infringing and/or unauthorized uses. This expressly includes the authority, but not the obligation, for us to send takedown notices (including, without limitation, pursuant to 17 U.S.C. § 512(c)(3) (i.e., DMCA Takedown Notices)) on your behalf if Your Content is taken and used by third parties outside of DatingPool.</p>

        <h3>Member Content</h3>
        <p>Other members of DatingPool will also share content via the App. Member Content belongs to the user who posted the content and is stored on our servers and displayed via the App at the direction of the user providing the Member Content. You may not use other users' information for commercial purposes, to spam, to harass, stalk or to make unlawful threats. We reserve the right to terminate your Account if you misuse other users' information. If you have a complaint about Member Content, please see the Digital Millennium Copyright Act (DMCA) section below for more information.</p>

        <h3>Our Content</h3>
        <p>Any other text, content, graphics, user interfaces, trademarks, logos, sounds, artwork, and other intellectual property appearing on DatingPool, as well as the DatingPool software and database(s), are owned, controlled or licensed by us and are protected by copyright, trademark, data, database rights and/or other intellectual property law rights. All right, title and interest in and to Our Content remains with us at all times.</p>
        <p>We grant you a non-exclusive, limited, personal, non-transferable, revocable, license to access and use Our Content, without the right to sublicense, under the following conditions:</p>
        <ul>
          <li>you shall not use, sell, modify, or distribute Our Content except as permitted by the functionality of the App;</li>
          <li>you shall not use our name in metatags, keywords and/or hidden text;</li>
          <li>you shall not create derivative works from Our Content or scrape, disable, decompile, analyze or in any way commercially exploit Our Content, in whole or in part, in any way; and</li>
          <li>you shall use Our Content for lawful purposes only.</li>
        </ul>
        <p>While we don't assume any obligation to pre-screen any of Your Content or any Member Content, there may be times where we need to step in to help keep our members safe, and we reserve the right to review, pre-screen, refuse and/or remove any Member Content and Your Content, including content exchanged between users in direct messages as set out in these Terms.</p>

        <h2>3. RESTRICTIONS ON THE APP</h2>
        <p>You agree to:</p>
        <ul>
          <li>comply with all applicable laws, including without limitation, privacy laws, intellectual property laws, anti-spam laws, equal opportunity laws and regulatory requirements;</li>
          <li>use your real name and real age in creating your DatingPool account and on your profile; and</li>
          <li>use the services in a safe, inclusive and respectful manner and adhere to our Community Guidelines at all times.</li>
        </ul>
        <p>You agree that you will not:</p>
        <ul>
          <li>act in an unlawful or disrespectful manner including being dishonest, abusive or discriminatory;</li>
          <li>misrepresent your identity, your age, your current or previous positions, qualifications or affiliations with a person or entity;</li>
          <li>disclose information that you do not have the consent to disclose;</li>
          <li>stalk or harass any other user of the App;</li>
          <li>use the App in any deceptive, inauthentic or manipulative way, including engaging in conduct or distributing content relating to scams, spam, inauthentic profiles or commercial and promotional activity;</li>
          <li>submit appeals, reports, notices or complaints that are manifestly unfounded; or;</li>
          <li>develop, support or use software, devices, scripts, robots, other types of mobile code or any other means or processes (including crawlers, browser plugins and add-on or other technology) to scrape or otherwise exfiltrate from DatingPool or its services, or otherwise copy profiles and other data from the services.</li>
        </ul>
        <p>You can report any abuse or complain about Member Content by contacting us, outlining the abuse and/or complaint. You can also report a user directly from a profile or in chat by clicking the 'Block & Report' link. We reserve the right to investigate any possible violations of these Terms, any DatingPool user's rights, or any third party rights and we may, in our sole discretion, immediately terminate any user's right to use of the App without prior notice, as set out further in Section 1 above, and/or remove any improper, infringing or otherwise unauthorized Member Content submitted to the App.</p>
        <p>We don't control any of the things our users say or do, so you are solely responsible for your interactions with other users of the App and you will indemnify, defend, release, and hold us harmless from any claims made in connection with anything you do or say on the App, on other online locations, or when meeting other users in person.</p>
        <p><strong>IN CERTAIN CIRCUMSTANCES, SUCH AS IN RESPONSE TO USER-GENERATED OR PRESS REPORTS OF SUSPECTED MISCONDUCT, DATINGPOOL MAY INVESTIGATE WHETHER A USER HAS A CRIMINAL HISTORY, WHICH MAY, DEPENDING ON THE CIRCUMSTANCES, INCLUDE SEARCHING SEX OFFENDER REGISTRIES OR OTHER PUBLIC RECORDS. IF SUCH INVESTIGATIONS IDENTIFY A PERSON WITH A CRIMINAL CONVICTION, DATINGPOOL MAY USE AVAILABLE INFORMATION TO DETERMINE WHETHER THE PERSON IDENTIFIED BY THE INVESTIGATION IS THE SAME PERSON AS THE USER ABOUT WHOM THE INVESTIGATION WAS CONDUCTED. FOLLOWING ANY SUCH INVESTIGATION, WITH RESPECT TO ANY USER THAT DATINGPOOL REASONABLY BELIEVES TO HAVE BEEN CONVICTED OF A SEX OFFENSE (SUCH AS SEXUAL ASSAULT OR SEXUAL HARASSMENT, AND INCLUDING ANY REGISTERED SEX OFFENDERS), OR A CONVICTION FOR HUMAN TRAFFICKING, STALKING, KIDNAPPING, CHILD ABUSE, DOMESTIC ABUSE, MURDER, HATE CRIMES, OR TERRORISM OR VIOLENT EXTREMISM, DATINGPOOL MAY TAKE STEPS TO BLOCK THAT PERSON FROM USING THE APP AND COMMUNICATING WITH OTHER USERS OVER THE DATINGPOOL PLATFORM(S). DATINGPOOL RESERVES THE RIGHT TO BLOCK USERS FOR OTHER OFFENSES, OR FOR OTHER VIOLATIONS OF THESE TERMS, OR FOR OTHER REASONS IN THEIR SOLE DISCRETION. CRIMINAL BACKGROUND INVESTIGATIONS, WHEN CONDUCTED, ARE NOT TYPICALLY UPDATED BY DATINGPOOL. ADDITIONALLY, WHILE INVESTIGATIONS FOR CRIMINAL HISTORIES MAY BE CONDUCTED ON SOME USERS, THEY ARE NOT FOOLPROOF AND MOST USERS ARE NOT EXPECTED TO BE SUBJECT TO ANY FORM OF CHECK FOR CRIMINAL HISTORIES. ANY INVESTIGATIONS FOR CRIMINAL HISTORIES MAY GIVE USERS A FALSE SENSE OF SECURITY. THE CHECKS FOR CRIMINAL HISTORIES THAT MAY BE CONDUCTED BY DATINGPOOL ARE NOT A PERFECT SAFETY SOLUTION. CRIMINALS MAY CIRCUMVENT EVEN THE MOST SOPHISTICATED SEARCH TECHNOLOGY. NOT ALL CRIMINAL RECORDS ARE PUBLIC IN ALL STATES AND NOT ALL DATABASES ARE UP TO DATE. ONLY PUBLICLY AVAILABLE CONVICTIONS ARE INCLUDED IN CHECKS, AND CHECKS DO NOT COVER OTHER TYPES OF CONVICTIONS OR ARRESTS OR ANY CONVICTIONS FROM FOREIGN COUNTRIES.</strong></p>
        <p>You agree to, and hereby do, release DatingPool and its successors from any claims, demands, losses, damages, rights, and actions of any kind, including personal injuries, death and property damage, that either directly or indirectly arises from your interactions with or conduct of other users of the App. If you are a California resident, you hereby waive California Civil Code Section 1542, which states, "A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party." The foregoing release does not apply to any claims, demands, or any losses, damages, rights and actions of any kind, including personal injuries, death or property damage for any unconscionable commercial practice by DatingPool or for such party's fraud, deception, false, promise, misrepresentation or concealment, suppression or omission of any material fact in connection with the App.</p>
        <p>Scraping or replicating any part of the App without our prior consent is expressly prohibited. This includes by any means (automated or otherwise) other than through our currently available, published interfaces.</p>
        <p>We may also suspend or close your Account where you have multiple Accounts.</p>
        <p>When necessary, we also may cooperate with law enforcement to assist in potential criminal investigations related to member conduct.</p>
        <p>Your treatment towards others outside of the App can also result in action against your Account. If we're made aware of harm between users on dates, meetups with friends, via text message or direct messaging platforms, or relevant alleged criminal or harmful conduct committed in your past or outside of the App, we may take action as if it happened on the App.</p>
        <p>You cannot submit appeals, reports, notices or complaints that are false reports or report for malicious, biased, or other illegitimate reasons.</p>

        <h2>4. Safety Measures</h2>
        <p>To use our App, you must be at least 18 years old or the age of majority to legally enter into a contract under the laws of your home country if that happens to be greater than 18. Please note that we monitor for underage use and we will terminate, suspend or ask you to verify your Account if we have reason to believe that you may be underage.</p>
        <p>We may require users to verify their identity in order to register an Account, or to continue using an Account, at any time. We also reserve the right to require users to provide a valid phone number registered to their Account and to verify it at any time. Please note that if you don't complete a verification request, you may be unable to register an Account or you may lose access to the App.</p>
        <p>You authorize your wireless carrier to use or disclose information about your Account and your wireless device, if available, to DatingPool or its service provider for the duration of your business relationship, solely to help them identify you or your wireless device and to prevent fraud.</p>
        <p>We use a combination of human moderators and automated systems to monitor and review user accounts and interactions for content that may be against our Community Guidelines, against our Terms, or otherwise harmful. If another user does anything that makes you feel uncomfortable or unsafe, we highly encourage you to unmatch with, block, and/or report the user. See this article for more info on what happens when you report something to DatingPool.</p>

        <h2>5. PRIVACY</h2>
        <p>For information about how DatingPool collects, uses, and shares your personal data, please check out our Privacy Policy. By using the App, you acknowledge that we may use such data in accordance with our Privacy Policy.</p>

        <h2>6. PAYMENT TERMS</h2>
        <h3>Generally.</h3>
        <p>DatingPool offers our App services as automatically-renewing subscriptions (e.g., a one-month subscription) ("Premium Services"), and our partners offer tickets for purchase in the App (each a "Ticket") for various events (each an "Event") that are of interest to users. If you choose to purchase a Ticket for an Event, you acknowledge and agree that additional terms, disclosed to you at the point of purchase, may apply, and that such additional terms are incorporated herein by reference.</p>
        <p>You may purchase Tickets and Premium Services subscriptions through the following payment methods ("Payment Method"): (a) making a purchase through a third-party platform such as the Apple App Store and Google Play Store ("Third Party Store"), or (b) paying with your credit card, debit card, or PayPal account, which will be processed by our third-party processor, such as Stipe ("Payment Processor"). Once you have made a purchase of a Ticket or subscription, you authorize us to charge your chosen Payment Method. If payment is not received by us from your chosen Payment Method, you agree to promptly pay all amounts due upon demand by us.</p>
        <h3>Ticket Resales.</h3>
        <p>We may allow you to resell Tickets to other users on through out in App resale marketplace. If you resell a Ticket on the App, we will transfer the Ticket to the purchasing user, and you will no longer be able to use the Ticket sold. You will determine the price you sell each Ticket for, but we do charge a fee to be deducted from the sale price for the applicable Ticket (the "Sale Fee"). The Sale Fee will be shown to you when you list each Ticket. Following the sale of each Ticket, the sale price of the Ticket will be paid to your Payment Method on file, less the applicable Sale Fee.</p>
        <p><strong>IF YOU PURCHASE AN AUTOMATICALLY RENEWING SUBSCRIPTION, YOUR SUBSCRIPTION WILL RENEW AT THE END OF THE PERIOD, UNLESS YOU CANCEL, AT DATINGPOOL'S THEN-CURRENT PRICE FOR SUCH SUBSCRIPTIONS.</strong></p>
        <p>To avoid charges for a new subscription period, you must cancel, as described below, before the end of the then-current subscription period. Deleting your Account or deleting the App from your device does not cancel your subscription. You will be given notice of changes in the pricing of the Premium Services to which you have subscribed and an opportunity to cancel. If DatingPool changes these prices and you do not cancel your subscription, you agree that you will be charged at DatingPool's then-current pricing for subscription.</p>
        <h3>Canceling Subscriptions.</h3>
        <p>If you purchased a subscription directly from DatingPool, you may cancel or change your Payment Method via the payment settings option under your Account. If you purchased a subscription through a Third Party Store, such as the Apple App Store or the Google Play Store, you will need to access your account with that Third Party Store and follow instructions to change or cancel your subscription. If you cancel your subscription, you may use your subscription until the end of the period you last paid for, but (i) you will not (except as set forth in the subsection entitled "Refunds" below) be eligible for a prorated refund, (ii) your subscription will not be renewed when that period expires and (iii) you will then no longer be able to use the Premium Services or Tickets enabled by your subscription.</p>
        <p>Because our services may be utilized without a subscription, canceling your subscription does not remove your Account from the App or our services. If you wish to fully terminate your Account, you must terminate your Account as set forth in Section 15 (Termination).</p>
        <p>We frequently offer promotional rates - which can vary based on region, length of subscription, bundle size and more. We also regularly test new features and payment options. DatingPool reserves the right, including without prior notice, to limit the available quantity of or discontinue making available any product, feature, service or other offering; to impose conditions on the honoring of any coupon, discount, offer or other promotion; to bar any user from making any transaction; and to refuse to provide any user with any product, service or other offering or to honor any offer.</p>
        <h3>Free Trials.</h3>
        <p>If you sign up for a free trial and do not cancel, your trial may convert into a paid subscription and your Payment Method will be charged at the then-current price for such subscription. Once your free trial converts to a paid subscription, your paid subscription will continue to automatically renew at the end of each period, and your Payment Method will be charged, until you cancel. To avoid charges for a new subscription period, you must cancel before the end of the then-current subscription period or free trial period as described above. Deleting your Account or deleting the App from your device does not cancel your free trial. If you have signed up for a free trial on DatingPool through the Apple Store or Google Play Store previously, you will not be eligible for another free trial and you will then be automatically signed up to a subscription and charged as described in this paragraph.</p>
        <h3>Refunds.</h3>
        <p>Generally, all charges for purchases are nonrefundable, and there are no refunds or credits for partially used periods.</p>
        <p>However, for subscribers residing in Arizona, California, Colorado, Connecticut, Illinois, Iowa, Minnesota, New York, North Carolina, Ohio, Rhode Island, and Wisconsin, the terms below apply:</p>
        <p><strong>YOU MAY CANCEL YOUR SUBSCRIPTION, WITHOUT PENALTY OR OBLIGATION, AT ANY TIME PRIOR TO MIDNIGHT OF THE THIRD BUSINESS DAY FOLLOWING THE DATE YOU SUBSCRIBED (EXCLUDING SUNDAYS AND HOLIDAYS). IN THE EVENT THAT YOU DIE BEFORE THE END OF YOUR SUBSCRIPTION PERIOD, YOUR ESTATE SHALL BE ENTITLED TO A REFUND OF THAT PORTION OF ANY PAYMENT YOU HAD MADE FOR YOUR SUBSCRIPTION WHICH IS ALLOCABLE TO THE PERIOD AFTER YOUR DEATH. IN THE EVENT THAT YOU BECOME DISABLED (SUCH THAT YOU ARE UNABLE TO USE THE APP) BEFORE THE END OF YOUR SUBSCRIPTION PERIOD, YOU SHALL BE ENTITLED TO A REFUND OF THAT PORTION OF ANY PAYMENT YOU HAD MADE FOR YOUR SUBSCRIPTION WHICH IS ALLOCABLE TO THE PERIOD AFTER YOUR DISABILITY BY PROVIDING DATINGPOOL NOTICE IN THE SAME MANNER AS YOU REQUEST A REFUND AS DESCRIBED BELOW.</strong></p>
        <p>Blocked members are not entitled to refunds.</p>
        <p>To request a refund: In addition to cancelling, eligible subscribers must request a refund to receive one.</p>
        <p>If you subscribed using your Apple ID, refunds are handled by Apple, not DatingPool. To request a refund, go to App Store, click on your Apple ID, select "Purchase history," find the transaction and hit "Report Problem." You can also submit a request at Apple Support.</p>
        <p>For all other purchases: please contact customer support with your order number (you can find the order number in the order confirmation email, or if you purchased from the Google Play Store by logging in to Google Wallet). You may also mail or deliver a signed and dated notice which states that you, the buyer, are cancelling this agreement, or words of similar effect. Please also include the email address or mobile number associated with your Account along with your order number. This notice shall be sent to: DatingPool, Attn.: Cancellations, 5473 Blair Rd Ste 100, Dallas, Texas 75231.</p>
        <h3>Taxes.</h3>
        <p>The payments required under this Section 6 do not include any Sales Tax that may be due in connection with the Premium Services or Tickets provided under these Terms. If DatingPool determines it has a legal obligation to collect a Sales Tax from you in connection with these Terms, DatingPool will collect such Sales Tax in addition to the payments required under this Section 6. If any Tickets Premium Services, or payments therefore, under these Terms are subject to any Sales Tax in any jurisdiction and you have not remitted the applicable Sales Tax to DatingPool, you will be responsible for the payment of such Sales Tax and any related penalties or interest to the relevant tax authority. As used herein, "Sales Tax" means any sales or use tax and any other tax measured by sales proceeds that is the functional equivalent of a sales tax where the applicable taxing jurisdiction does not otherwise impose a sales or use tax.</p>

        <h2>7. VIRTUAL ITEMS</h2>
        <p>At times, you may be able to purchase a limited, personal, non-transferable, non-sublicensable, revocable license to access special limited-use features from DatingPool, referred to here as "Virtual Items." You can only purchase Virtual Items through DatingPool or DatingPool's partners. Virtual Items represent a limited license right governed by this Agreement, and, except as otherwise prohibited by applicable law, no title or ownership in or to Virtual Items is being transferred or assigned to you. This Agreement, and your purchase of Virtual Items, does not constitute the sale of any rights in Virtual Items.</p>
        <p>Any Virtual Item balance shown in your account does not constitute a real-world balance or reflect any stored value, but instead shows the extent of your license to access Virtual Items. Virtual Items do not incur fees for non-use. Your license in Virtual Items will terminate on the earlier of DatingPool ceasing provision of services or your account closing or terminating. DatingPool may also at times provide Virtual Items as bonuses to, or parts of, paid subscriptions for its services. Your ability to use Virtual Items you have access to in this manner may terminate at the end of each of your subscription periods and your access to Virtual Items may not "roll over" or accumulate through additional subscription periods. Your access to Virtual Items gained through subscriptions may also end if you cancel your subscription.</p>
        <p>DatingPool, in its sole discretion, reserves the right to charge fees for the right to access or use Virtual Items and/or may distribute Virtual Items with or without charge. DatingPool may manage, regulate, control, modify, or eliminate Virtual Items at any time, including taking actions that may impact the perceived value or purchase price, if applicable, of any Virtual Items and DatingPool shall have no liability to you for doing so. You shall not sell, redeem, or otherwise transfer Virtual Items to any person or entity. Virtual Items may only be redeemed through our Services.</p>
        <p><strong>ALL PURCHASES AND REDEMPTIONS OF VIRTUAL ITEMS MADE THROUGH OUR SERVICES ARE FINAL AND NON-REFUNDABLE. YOU ACKNOWLEDGE THAT DATINGPOOL IS NOT REQUIRED TO PROVIDE A REFUND FOR ANY REASON, AND THAT YOU WILL NOT RECEIVE MONEY OR OTHER COMPENSATION FOR UNUSED VIRTUAL ITEMS WHEN AN ACCOUNT IS CLOSED, WHETHER SUCH CLOSURE WAS VOLUNTARY OR INVOLUNTARY.</strong></p>

        <h2>8. PUSH NOTIFICATIONS; LOCATION-BASED FEATURES</h2>
        <p>We may provide you with emails, text messages, push notifications, alerts and other messages related to the App and/or the DatingPool services, such as enhancements, offers, products, events, and other promotions. After downloading the App, you will be asked to accept or deny push notifications/alerts. If you deny, you will not receive any push notifications/alerts. If you accept, push notifications/alerts will be automatically sent to you. If you no longer wish to receive push notifications/alerts from the App, you may opt out by changing your notification settings on your mobile device. With respect to other types of messaging or communications, such as emails, text messages, etc., you can unsubscribe or opt out by either following the specific instructions included in such communications, or by emailing us with your request at dev@datingpool.ai.</p>
        <p>The App may allow access to or make available opportunities for you to view certain content and receive other products, services and/or other materials based on your location. To make these opportunities available to you, the App will determine your location using one or more reference points, such as GPS, Bluetooth and/or software within your mobile device. If you have set your mobile device to disable GPS, Bluetooth or other location determining software or do not authorize the App to access your location data, you will not be able to access such location-specific content, products, services and materials. For more about how the App uses and retains your information, please read the Privacy Policy.</p>

        <h2>9. DISCLAIMER</h2>
        <p><strong>THE APP, OUR CONTENT, TICKETS, AND MEMBER CONTENT ARE ALL PROVIDED TO YOU "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, WE DO NOT GUARANTEE THE COMPATIBILITY BETWEEN YOU AND ANY OTHER USER.</strong></p>
        <p><strong>SHOULD APPLICABLE LAW NOT PERMIT THE FOREGOING EXCLUSION OF EXPRESS OR IMPLIED WARRANTIES, THEN WE GRANT THE MINIMUM EXPRESS OR IMPLIED WARRANTY REQUIRED BY APPLICABLE LAW. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, SHALL CREATE ANY WARRANTY, REPRESENTATION OR GUARANTEE NOT EXPRESSLY STATED IN THIS SECTION.</strong></p>
        <p><strong>ADDITIONALLY, WE DO NOT MAKE ANY WARRANTIES THAT THE APP WILL BE UNINTERRUPTED, SECURE OR ERROR FREE OR THAT YOUR USE OF THE APP WILL MEET YOUR EXPECTATIONS, OR THAT THE APP, OUR CONTENT, ANY MEMBER CONTENT, TICKETS, OR ANY PORTION THEREOF, IS CORRECT, ACCURATE, OR RELIABLE. YOUR USE OF THE APP AND ATTENDANCE OF ANY AND ALL EVENTS IS AT YOUR OWN RISK. YOU ARE SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER USERS OR AT EVENTS. DATINGPOOL IS NOT RESPONSIBLE FOR THE CONDUCT OF ANY USER.</strong></p>

        <h2>10. LIMITATION OF LIABILITY</h2>
        <p><strong>NEITHER US NOR ANY EVENT ORGANIZER WILL BE LIABLE FOR ANY DAMAGES, DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR PUNITIVE, INCLUDING, WITHOUT LIMITATION, LOSS OF DATA, INCOME, PROFIT OR GOODWILL, LOSS OF OR DAMAGE TO PROPERTY AND CLAIMS OF THIRD PARTIES ARISING OUT OF YOUR ACCESS TO OR USE OF THE APP, A TICKET, OUR CONTENT, OR ANY MEMBER CONTENT, HOWEVER CAUSED, WHETHER BASED ON BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), PROPRIETARY RIGHTS INFRINGEMENT, PRODUCT LIABILITY OR OTHERWISE.</strong></p>
        <p><strong>THE FOREGOING SHALL APPLY EVEN IF WE WERE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF YOU BECOME DISSATISFIED IN ANY WAY WITH THE APP OR TICKETS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO STOP YOUR USE OF THE APP. YOU HEREBY WAIVE ANY AND ALL CLAIMS ARISING OUT OF YOUR USE OF THE APP OR ANY TICKET. BECAUSE SOME STATES DO NOT ALLOW THE DISCLAIMER OF IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN TYPES OF DAMAGES, THESE PROVISIONS MAY NOT APPLY TO YOU. IF ANY PORTION OF THIS LIMITATION ON LIABILITY IS FOUND TO BE INVALID OR UNENFORCEABLE FOR ANY REASON, THEN OUR AGGREGATE LIABILITY SHALL NOT EXCEED ONE HUNDRED DOLLARS ($100).</strong></p>
        <p><strong>THE LIMITATION OF LIABILITY HEREIN IS A FUNDAMENTAL ELEMENT OF THE BASIS OF THE BARGAIN AND REFLECTS A FAIR ALLOCATION OF RISK. THE APP WOULD NOT BE PROVIDED WITHOUT SUCH LIMITATIONS AND YOU AGREE THAT THE LIMITATIONS AND EXCLUSIONS OF LIABILITY, DISCLAIMERS AND EXCLUSIVE REMEDIES SPECIFIED HEREIN WILL SURVIVE EVEN IF FOUND TO HAVE FAILED IN THEIR ESSENTIAL PURPOSE. THE FOREGOING DOES NOT APPLY TO LIABILITY ARISING FROM ANY FRAUD OR FRAUDULENT MISREPRESENTATIONS, OR ANY OTHER LIABILITY THAT CANNOT BE LIMITED BY APPLICABLE LAW.</strong></p>

        <h2>11. INDEMNITY</h2>
        <p>All the actions you make and information you post on the App remains your responsibility. Therefore, you agree to indemnify, defend, release, and hold us, and our partners, licensors, affiliates, contractors, officers, directors, employees, representatives and agents, harmless, from and against any third party claims, damages (actual and/or consequential), actions, proceedings, demands, losses, liabilities, costs and expenses (including reasonable legal fees) suffered or reasonably incurred by us arising as a result of, or in connection with: any negligent acts, omissions or willful misconduct by you; your access to and use of the App; the uploading or submission of Content to the App by you; any breach of these Terms by you; and/or your violation of any law or of any rights of any third party.</p>
        <p>We retain the exclusive right to settle, compromise and pay any and all claims or causes of action which are brought against us without your prior consent. If we ask, you will co-operate fully and reasonably as required by us in the defense of any relevant claim.</p>

        <h2>12. DIGITAL MILENNIUM COPYRIGHT ACT (DMCA)</h2>
        <p>If you believe any content on DatingPool infringes the copyright in a work that you own, please submit a notification alleging such infringement ("DMCA Takedown Notice") to DatingPool's Copyright Agent. The Takedown Notice must include the following: A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works; Identification of the material claimed to be infringing or to be the subject of infringing activity and that is to be removed or access disabled and information reasonably sufficient to permit the service provider to locate the material; Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail; A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and A statement that, under penalty of perjury, the information in the notification is accurate and you are authorized to act on behalf of the owner of the exclusive right that is allegedly infringed.</p>
        <p>Takedown Notices should be sent to DatingPool's Copyright Agent at dev@datingpool.ai. If you wish to reach out to DatingPool's Copyright Agent via other methods, you can write to: DatingPool, Attn: DatingPool Copyright Agent, 5473 Blair Rd Ste 100, Dallas, Texas 75231.</p>

        <h2>14. DISPUTE RESOLUTION; ARBITRATION</h2>
        <p>Please read the following arbitration agreement in this Section ("Arbitration Agreement") carefully. Unless you opt out in the manner described in Section 14.7 below, this Arbitration Agreement requires you and DatingPool to resolve disputes by binding arbitration instead of in court, and limits the manner in which we may seek relief from each other.</p>
        <h3>14.1 Choice of Law and Venue.</h3>
        <p>These Terms and your use of the App are governed by and construed in accordance with the laws of the State of Texas applicable to agreements made and to be entirely performed within the State of Texas, without regard to its conflict of law principles. Except as explicitly outlined below or elsewhere in these Terms, any dispute between the parties shall be resolved in the state or federal courts of Texas and the United States, respectively, sitting in Dallas, Texas and you hereby consent to such jurisdiction and waive all defenses of lack of personal jurisdiction and forum non conveniens with respect to venue and jurisdiction in such state and federal courts.</p>
        <h3>14.2 Informal Negotiations.</h3>
        <p>To expedite resolution and control the cost of any dispute, controversy, or claim related to these Terms (each a "Dispute" and collectively, the "Disputes") brought by either you or us (individually, a "Party" and collectively, the "Parties"), the Parties agree to first attempt to negotiate any Dispute (except those Disputes expressly provided below) informally for at least thirty (30) days before initiating arbitration. Such informal negotiations commence upon written notice from one Party to the other Party.</p>
        <h3>14.3 Binding Arbitration.</h3>
        <p>If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally and exclusively resolved by binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association ("AAA") and, where appropriate, the AAA's Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are available at the American Arbitration Association (AAA) website. Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules. If such costs are determined by the arbitrator to be excessive, we will pay all arbitration fees and expenses. The arbitration may be conducted in person, through the submission of documents, by phone, or online. The arbitrator will make a decision in writing but need not provide a statement of reasons unless requested by either Party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in Dallas, Texas. Except as otherwise provided herein, the Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator. If for any reason, a Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the state and federal courts located in Dallas, Texas, as outlined above. Application of the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transaction Act (UCITA) are excluded from these Terms.</p>
        <p>Restrictions. The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.</p>
        <p>Exceptions to Informal Negotiations and Arbitration. The Parties agree that the following Disputes are not subject to the above provisions concerning informal negotiations and binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use; and (c) any claim for injunctive relief.</p>
        <p>If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.</p>
        <h3>14.4 Class Action Waiver.</h3>
        <p>You waive the right to serve as a class representative, class member, or otherwise participate in any class, collective, consolidated, or representative proceeding against us related to any disputes arising under these Terms. You agree that this class action waiver is material and essential to the resolution of any dispute and is non-severable from these Terms and your use of the Services.</p>
        <h3>14.5 Waiver of Jury Trial.</h3>
        <p><strong>YOU HEREBY ACKNOWLEDGE THAT BY ENTERING INTO THESE TERMS AND USING THE APP, YOU KNOWINGLY AND VOLUNTARILY WAIVE THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION. ALL DISPUTES SHALL BE RESOLVED THROUGH BINDING ARBITRATION ON AN INDIVIDUAL BASIS ONLY.</strong></p>
        <h3>14.6 Limitation on Time to File Claims.</h3>
        <p><strong>ANY DISPUTE, CAUSE OF ACTION, OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF USE OR THE APP MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE DISPUTE, CAUSE OF ACTION, OR CLAIM ACCRUES; OTHERWISE, SUCH DISPUTE, CAUSE OF ACTION, OR CLAIM IS PERMANENTLY BARRED.</strong></p>
        <h3>14.7 Opt-Out.</h3>
        <p>Updates to DatingPool's Terms do not provide a new opportunity for you to opt out of arbitration if you previously agreed to a prior version of DatingPool's Terms containing an arbitration provision and did not validly opt out of arbitration. Users who previously agreed to arbitrate may reject this updated Arbitration Agreement by following the opt-out method below, but such users will still be bound by the most recent prior version of the Arbitration Agreement and will otherwise be bound by these Terms. Previous or existing users who do not opt out of this updated Arbitration Agreement will be bound by this Arbitration Agreement and it shall apply to all disputes between such users and DatingPool, including those arising (but not actually filed in arbitration) before the effective date of these Terms. Arbitration demands that have already been actually filed with an arbitration provider before the effective date of this Arbitration Agreement and in compliance with a prior version of this Arbitration Agreement are subject to the prior version's terms. Subject to the above, you may opt out of this Arbitration Agreement by sending written notice of your decision to opt out to dev@datingpool.ai within 31 days after first becoming subject to this Arbitration Agreement. Your notice must include your name, your DatingPool username (if any), the email address and/or phone number you used to set up your Account (if you have one), and an unequivocal statement that you want to opt out of this Arbitration Agreement. If you opt out of this Arbitration Agreement, all other parts of the Terms and any other agreements between you and DatingPool will continue to apply to you. Opting out of this Arbitration Agreement has no effect on any other arbitration agreements that you may currently have, or may enter in the future, with us.</p>
        <h3>14.8 Survival of Agreement.</h3>
        <p>The terms of this Arbitration Agreement will continue, even after your relationship with DatingPool has ended.</p>

        <h2>15. TERMINATION</h2>
        <p>These Terms commence on the date you accept them (as described in the preamble) and continue until terminated in accordance with the terms herein.</p>
        <p>You can delete your Account at any time by logging into the App, going to the "Settings" tab (the gear icon), and following the instructions to terminate your Account. Please note that if you delete your Account, your subscription will continue until the end of the subscription period for which applicable fees have been paid, and you will not be entitled to a refund except as stated in Section 6. In addition to deleting your Account, you will also need to cancel/manage any recurring subscriptions purchased via a Third Party Store (e.g., Apple App Store, Google Play) to avoid additional billing.</p>
        <p>In the event that DatingPool determines, in its sole discretion, that you have breached any portion of these Terms, have misused the App, or have otherwise demonstrated conduct which DatingPool regards as inappropriate or unlawful (whether on or off the App), DatingPool reserves the right to: (a) warn you via email (to any email addresses you have provided to DatingPool) that you have violated the Terms; (b) delete your User Content; (c) discontinue your Account; (d) discontinue your subscription(s) or Tickets without refund; (e) notify and/or send your User Content to and/or fully cooperate with the proper law enforcement authorities for further action; and/or (f) pursue to any other action which DatingPool deems to be appropriate. You agree that all terminations for cause shall be made in DatingPool's sole discretion and that DatingPool shall not be liable to you or any third party for any termination of your Account.</p>
        <p>Termination of these Terms or your Account includes the removal of access to your Account, and all related information and content associated with or inside your Account.</p>
        <p>If your Account is terminated by you or by DatingPool for any reason, all provisions of these Terms which by their nature should survive, shall survive termination of these Terms, including, without limitation, the Arbitration Agreement, ownership provisions, warranty disclaimers and limitation of liability. Your information will be maintained and deleted in accordance with our Privacy Policy.</p>

        <h2>16. MISCELLANEOUS</h2>
        <p>These Terms, which we may amend from time to time, constitute the entire agreement between you and DatingPool. We might have to make changes to these Terms so we reserve the right to modify, amend or change the Terms at any time (a "Change"). If we do this then the Changes will be posted on this page and we will indicate the Effective Date of the updates at the top of the Terms. In certain circumstances, we may send an email to you notifying you of a Change. You should regularly check this page for notice of any Changes. Your continued use of DatingPool following any Change constitutes your acceptance of the Change and you will be legally bound by the new updated Terms. If you do not accept any Changes to the Terms, you should stop using DatingPool immediately. The Terms supersede all previous agreements, representations and arrangements between us (written or oral), excluding the Privacy Policy. Nothing in this clause shall limit or exclude any liability for fraudulent misrepresentation.</p>
        <p>The communications between you and DatingPool may take place via electronic means, whether you use the App or send DatingPool emails, or whether DatingPool posts notices in the App or communicates with you via email. For contractual purposes, you (a) consent to receive communications from DatingPool in electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that DatingPool provides to you electronically satisfy if it were to be in writing. The foregoing does not affect your statutory rights, including but not limited to the Electronic Signatures in Global and National Commerce Act at 15 U.S.C. Sec. 7001 et. seq.</p>
        <p>If, for any reason, any of the Terms are declared illegal, invalid or otherwise unenforceable by a court of a competent jurisdiction, then to the extent that term is illegal, invalid or unenforceable, it shall be severed and deleted from the Terms and the remainder of the Terms shall survive, remain in full force and effect and continue to be binding and enforceable.</p>
        <p>No failure or delay in exercising any right, power or privilege under the Terms shall operate as a waiver of such right or acceptance of any variation of the Terms and nor shall any single or partial exercise by either party of any right, power or privilege preclude any further exercise of the right or the exercise of any other right, power or privilege.</p>
        <p>The App may contain links to third-party websites or resources. In such cases, you acknowledge and agree that we are not responsible or liable for (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources. Framing, in-line linking or other methods of association with the App are expressly prohibited without first obtaining our prior written approval.</p>
        <p>If you have any questions, complaints or claims with respect to the App, please contact us at dev@datingpool.ai.</p>

        <h2>18. GOVERNING LAW AND FORUM</h2>
        <p>These Terms are governed and interpreted by the laws of the State of Texas. All claims arising out of or relating to these Terms and/or your relationship with DatingPool that for whatever reason are not submitted to arbitration, and all claims or cases challenging the enforceability or applicability of the arbitration provisions herein, will be litigated exclusively in the federal or state courts of Dallas, Texas. You agree that such courts shall have personal jurisdiction and venue and waive any objection based on inconvenient forum. You agree that you will not file or participate in a class action against us.</p>
      </div>
    </PlaceholderLayout>
  )
}
